name = "universal-net-calc"
main = ".open-next/worker.js"
compatibility_date = "2024-01-01"
assets = { directory = ".open-next/assets", binding = "ASSETS" }
workers_dev = true

[[kv_namespaces]]
binding = "EXCHANGE_RATES_CACHE"
id = "23769d8b2bf540acb3f6118c87e45f29"

[[kv_namespaces]]
binding = "FEEDBACK"
id = "bd28fcf4ed2c44c2a58188a9be18bab2"

[env.preview]
name = "universal-net-calc-preview"

[[env.preview.kv_namespaces]]
binding = "EXCHANGE_RATES_CACHE"
id = "23769d8b2bf540acb3f6118c87e45f29"

[[env.preview.kv_namespaces]]
binding = "FEEDBACK"
id = "bd28fcf4ed2c44c2a58188a9be18bab2"

[env.production]

[[env.production.kv_namespaces]]
binding = "EXCHANGE_RATES_CACHE"
id = "23769d8b2bf540acb3f6118c87e45f29"

[[env.production.kv_namespaces]]
binding = "FEEDBACK"
id = "bd28fcf4ed2c44c2a58188a9be18bab2"
